# CMake generated Testfile for 
# Source directory: /home/iannuz/popf-tif/planner/src/popf/testcases/TILTests
# Build directory: /home/iannuz/popf-tif/planner/debug/popf/testcases/TILTests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(satellite-time-TILs "/home/iannuz/popf-tif/planner/debug/popf/popf2" "-I" "-D" "-c" "-r" "-s" "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/satellite-domain.pddl" "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/satellite-problem.pddl" "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/satellite-plan")
set_tests_properties(satellite-time-TILs PROPERTIES  _BACKTRACE_TRIPLES "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/CMakeLists.txt;1;add_test;/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/CMakeLists.txt;0;")
add_test(satellite-complextime-TILs "/home/iannuz/popf-tif/planner/debug/popf/popf2" "-I" "-D" "-c" "-r" "-s" "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/satellite-complex-domain.pddl" "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/satellite-complex-problem.pddl" "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/satellite-complex-plan")
set_tests_properties(satellite-complextime-TILs PROPERTIES  _BACKTRACE_TRIPLES "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/CMakeLists.txt;2;add_test;/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/CMakeLists.txt;0;")
add_test(simple-TIL-fluents "/home/iannuz/popf-tif/planner/src/popf/testcases/popf2thenvalidate" "/home/iannuz/popf-tif/planner/debug/VALfiles/validate" "/home/iannuz/popf-tif/planner/debug/popf/popf3-cplex" "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/simple-TIL-fluent-domain.pddl" "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/simple-TIL-fluent-problem.pddl")
set_tests_properties(simple-TIL-fluents PROPERTIES  _BACKTRACE_TRIPLES "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/CMakeLists.txt;4;add_test;/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/CMakeLists.txt;0;")
add_test(invariants-with-TIL-fluents "/home/iannuz/popf-tif/planner/src/popf/testcases/popf2thenvalidate" "/home/iannuz/popf-tif/planner/debug/VALfiles/validate" "/home/iannuz/popf-tif/planner/debug/popf/popf3-cplex" "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/TIL-fluent-invariant-domain.pddl" "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/TIL-fluent-invariant-problem.pddl")
set_tests_properties(invariants-with-TIL-fluents PROPERTIES  _BACKTRACE_TRIPLES "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/CMakeLists.txt;5;add_test;/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/CMakeLists.txt;0;")
add_test(TIL-propositional-goal-persistence "/home/iannuz/popf-tif/planner/src/popf/testcases/popf2thenvalidate" "/home/iannuz/popf-tif/planner/debug/VALfiles/validate" "/home/iannuz/popf-tif/planner/debug/popf/popf3-cplex" "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/TIL-propositional-goal-persistence-domain.pddl" "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/TIL-propositional-goal-persistence-problem.pddl")
set_tests_properties(TIL-propositional-goal-persistence PROPERTIES  _BACKTRACE_TRIPLES "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/CMakeLists.txt;7;add_test;/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/CMakeLists.txt;0;")
add_test(TIL-numeric-goal-persistence "/home/iannuz/popf-tif/planner/src/popf/testcases/popf2thenvalidate" "/home/iannuz/popf-tif/planner/debug/VALfiles/validate" "/home/iannuz/popf-tif/planner/debug/popf/popf3-cplex" "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/TIL-numeric-goal-persistence-domain.pddl" "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/TIL-numeric-goal-persistence-problem.pddl")
set_tests_properties(TIL-numeric-goal-persistence PROPERTIES  _BACKTRACE_TRIPLES "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/CMakeLists.txt;8;add_test;/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/CMakeLists.txt;0;")
add_test(TIL-numeric-and-propositional-goal-persistence "/home/iannuz/popf-tif/planner/src/popf/testcases/popf2thenvalidate" "/home/iannuz/popf-tif/planner/debug/VALfiles/validate" "/home/iannuz/popf-tif/planner/debug/popf/popf3-cplex" "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/TIL-numeric-and-propositional-goal-persistence-domain.pddl" "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/TIL-numeric-and-propositional-goal-persistence-problem.pddl")
set_tests_properties(TIL-numeric-and-propositional-goal-persistence PROPERTIES  _BACKTRACE_TRIPLES "/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/CMakeLists.txt;9;add_test;/home/iannuz/popf-tif/planner/src/popf/testcases/TILTests/CMakeLists.txt;0;")
