# CMake generated Testfile for 
# Source directory: /home/iannuz/popf-tif-v2/planner/src/VALfiles/testing/pipes-strips-1
# Build directory: /home/iannuz/popf-tif-v2/planner/release/VALfiles/testing/pipes-strips-1
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pipes-notankage-pfile1-plan-steps-should-exist "/home/iannuz/popf-tif-v2/planner/src/VALfiles/testing/checkplanstepsexist" "/home/iannuz/popf-tif-v2/planner/release/VALfiles/testing/insttest" "/home/iannuz/popf-tif-v2/planner/src/VALfiles/testing/pipes-strips-1/pipesworld-notankage_nontemporal-strips-domain.pddl" "/home/iannuz/popf-tif-v2/planner/src/VALfiles/testing/pipes-strips-1/pipesworld-notankage_nontemporal-strips-problem.pddl" "/home/iannuz/popf-tif-v2/planner/src/VALfiles/testing/pipes-strips-1/pipesworld-notankage_nontemporal-strips-plan")
set_tests_properties(pipes-notankage-pfile1-plan-steps-should-exist PROPERTIES  _BACKTRACE_TRIPLES "/home/iannuz/popf-tif-v2/planner/src/VALfiles/testing/pipes-strips-1/CMakeLists.txt;1;add_test;/home/iannuz/popf-tif-v2/planner/src/VALfiles/testing/pipes-strips-1/CMakeLists.txt;0;")
add_test(pipes-tankage-pfile1-plan-steps-should-exist "/home/iannuz/popf-tif-v2/planner/src/VALfiles/testing/checkplanstepsexist" "/home/iannuz/popf-tif-v2/planner/release/VALfiles/testing/insttest" "/home/iannuz/popf-tif-v2/planner/src/VALfiles/testing/pipes-strips-1/pipesworld-tankage_nontemporal-strips-domain.pddl" "/home/iannuz/popf-tif-v2/planner/src/VALfiles/testing/pipes-strips-1/pipesworld-tankage_nontemporal-strips-problem.pddl" "/home/iannuz/popf-tif-v2/planner/src/VALfiles/testing/pipes-strips-1/pipesworld-tankage_nontemporal-strips-plan")
set_tests_properties(pipes-tankage-pfile1-plan-steps-should-exist PROPERTIES  _BACKTRACE_TRIPLES "/home/iannuz/popf-tif-v2/planner/src/VALfiles/testing/pipes-strips-1/CMakeLists.txt;2;add_test;/home/iannuz/popf-tif-v2/planner/src/VALfiles/testing/pipes-strips-1/CMakeLists.txt;0;")
